language: python
python:
  - 2.7
  - pypy
  - 3.6
install:
    #  - pip install -e . --use-mirrors
  - pip install -r python/requirements.txt
  - pip install coverage python-coveralls pep8
script:
  - nosetests --with-coverage --cover-package yalix -w python/src
after_success:
  - coveralls
