language: python
python:
  - 2.7
  - pypy
  - 3.2
  - 3.3
  - 3.4
install:
    #  - pip install -e . --use-mirrors
  - pip install -r src/python/requirements.txt
  - pip install coverage python-coveralls pep8
script:
  - nosetests --with-coverage --cover-package yalix -w src/python
after_success:
  - coveralls
