language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
    #  - pip install -e . --use-mirrors
  - pip install -r src/python/requirements.txt --use-mirrors
  - pip install coverage --use-mirrors
  - pip install python-coveralls --use-mirrors
script:
  - nosetests --with-coverage --cover-package yalix -w src/python
after_success:
  - coveralls
