name: Python test

on:
  push:
    paths:
      - "python/**"
      - ".github/workflows/python.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: python
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
          pipenv install -d
      - name: Lint
        continue-on-error: true
        working-directory: python
        run: |
          pipenv run flake8 --statistics .
      - name: Test
        working-directory: python
        run: |
          pipenv run python -m unittest ./tests/*_test.py
